### ISSUE TITLE
createTelegram is not an exportedmember

### ISSUE THREAD

**Issue by akliluberihun** [kolirt/vue-telegram-mini-app#1]
### Version

0.0.6

### Package configuration

createTelegram({
  alwaysExpand: true,
  closingConfirmation: true
})

### Steps to reproduce

try 

createTelegram({
  alwaysExpand: true,
  closingConfirmation: true
})

### Describe the bug

[Bug]:  CreateTelegram is not an exported member of the package, I found out that createTelegramMiniApp is the name, please either modify the doc README or the methodname

**Comment by kolirt** [comment]
@akliluberihun fixed

**Comment by akliluberihun** [comment]
Thanks
